== ri-collection-explicit-feedback-google-play-page Integration image:https://img.shields.io/badge/License-EPL%202.0-blue.svg["EPL 2.0", link="https://www.eclipse.org/legal/epl-2.0/"]
This plugin was created as a result of the OpenReq project funded by the European Union Horizon 2020 Research and Innovation programme under grant agreement No 732463.

== Notice:
This microservice is not maintained.

== Used Technologies
- Go (-> https://github.com/golang/go)
- Gorilla Mux (-> https://github.com/gorilla/mux)

== Functionalities 
The goal of this microservice is to collect all available metadata of an app page from the Google Play Store such as the name of the app, the category, and the average rating. 
The response contains all information with respect to that app page in JSON format.


== How to Run The microservice
Run the following commands to start the microservice:

1) docker build -t ri-collection-explicit-feedback-google-play-page .

2) docker run -p 9622:9622 ri-collection-explicit-feedback-google-play-page


== Public APIs
- link:http://217.172.12.199/registry/#/services/ri-collection-explicit-feedback-google-play-page[Rendered Documentation]


== How to contribute
See OpenReq project contribution link:[guidelines]

== License
Free use of this software is granted under the terms of the EPL version 2 (EPL2.0).